export const moveRangeMap = {
  boardHexes: {
    // '-1,0,1': {
    //   q: -1,
    //   r: 0,
    //   s: 1,
    //   id: '-1,0,1',
    //   occupyingUnitID: '',
    //   isUnitTail: false,
    //   altitude: 1,
    //   terrain: 'grass',
    //   startzonePlayerIDs: ['2'],
    // },
    // '-1,1,0': {
    //   q: -1,
    //   r: 1,
    //   s: 0,
    //   id: '-1,1,0',
    //   occupyingUnitID: '',
    //   isUnitTail: false,
    //   altitude: 1,
    //   terrain: 'grass',
    //   startzonePlayerIDs: ['4'],
    // },
    '0,-1,1': {
      q: 0,
      r: -1,
      s: 1,
      id: '0,-1,1',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 1,
      terrain: 'grass',
      startzonePlayerIDs: ['0'],
    },
    '0,0,0': {
      q: 0,
      r: 0,
      s: 0,
      id: '0,0,0',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 1,
      terrain: 'grass',
      startzonePlayerIDs: [],
    },
    '0,1,-1': {
      q: 0,
      r: 1,
      s: -1,
      id: '0,1,-1',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 1,
      terrain: 'grass',
      startzonePlayerIDs: ['1'],
    },
    // '1,-1,0': {
    //   q: 1,
    //   r: -1,
    //   s: 0,
    //   id: '1,-1,0',
    //   occupyingUnitID: '',
    //   isUnitTail: false,
    //   altitude: 1,
    //   terrain: 'grass',
    //   startzonePlayerIDs: ['5'],
    // },
    '1,0,-1': {
      q: 1,
      r: 0,
      s: -1,
      id: '1,0,-1',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 1,
      terrain: 'grass',
      startzonePlayerIDs: ['3'],
    },
  },
  hexMap: {
    mapId: 'moveRangeMap',
    mapShape: 'hexagon',
    mapName: 'Move Range Test Map',
    flat: false,
    mapSize: 1,
    hexSize: 10,
    mapWidth: 1,
    mapHeight: 1,
    glyphs: {
      // '0,0,0': {
      //   hexID: '0,0,0',
      //   glyphID: 'move',
      //   isRevealed: true,
      // },
    },
  },
}
