export const moveRange2HexWalkTestHexIDs = {
  initialHead_id: '0,1,-1',
  initialTail_id: '1,1,-2',
  // not updated below
  safeAdjacentSameLevel_id: '1,0,-1',
  engagedAdjacentSameLevel_id: '0,0,0',
  disengageOne_id: '-2,1,1',
  basicAdjacentFall_id: '-1,1,0',
  majorAdjacentFall_id: '-1,2,-1',
  majorFallOnly_id: '-2,3,-1',
  // cannotClimbOver_id: '-2,3,-1',
  disengageOneAndFall_id: '-2,0,2',
  revealedGlyph_id: '0,2,-2',
  beyondRevealedGlyph_id: '0,3,-3',
}

export const moveRangeTest2HexWalkMap = {
  boardHexes: {
    [moveRange2HexWalkTestHexIDs.initialHead_id]: {
      q: 0,
      r: 1,
      s: -1,
      id: moveRange2HexWalkTestHexIDs.initialHead_id,
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 5,
      terrain: 'grass',
      startzonePlayerIDs: ['1'],
    },
    [moveRange2HexWalkTestHexIDs.initialTail_id]: {
      q: 1,
      r: 1,
      s: -2,
      id: moveRange2HexWalkTestHexIDs.initialTail_id,
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 5,
      terrain: 'grass',
      startzonePlayerIDs: ['1'],
    },
    '0,-1,1': {
      // player 1's enemy unit
      q: 0,
      r: -1,
      s: 1,
      id: '0,-1,1',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 5,
      terrain: 'grass',
      startzonePlayerIDs: ['0'],
    },
    [moveRange2HexWalkTestHexIDs.basicAdjacentFall_id]: {
      // adjacent fall, jumping into a hole
      q: -1,
      r: 1,
      s: 0,
      id: moveRange2HexWalkTestHexIDs.basicAdjacentFall_id,
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 1,
      terrain: 'grass',
      startzonePlayerIDs: [''],
    },
    [moveRange2HexWalkTestHexIDs.majorAdjacentFall_id]: {
      // adjacent fall, jumping into a hole
      q: -1,
      r: 2,
      s: -1,
      id: moveRange2HexWalkTestHexIDs.majorAdjacentFall_id,
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: -9,
      terrain: 'grass',
      startzonePlayerIDs: [''],
    },
    [moveRange2HexWalkTestHexIDs.majorFallOnly_id]: {
      q: -2,
      r: 3,
      s: -1,
      id: moveRange2HexWalkTestHexIDs.majorFallOnly_id,
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: -9,
      terrain: 'grass',
      startzonePlayerIDs: [''],
    },
    [moveRange2HexWalkTestHexIDs.disengageOne_id]: {
      // the disengagement of bad-guy-1
      q: -2,
      r: 1,
      s: 1,
      id: moveRange2HexWalkTestHexIDs.disengageOne_id,
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 5,
      terrain: 'grass',
      startzonePlayerIDs: [''],
    },
    [moveRange2HexWalkTestHexIDs.disengageOneAndFall_id]: {
      // the disengagement of bad-guy-1
      q: -2,
      r: 0,
      s: 2,
      id: moveRange2HexWalkTestHexIDs.disengageOneAndFall_id,
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 1,
      terrain: 'grass',
      startzonePlayerIDs: [''],
    },
    '-1,-1,2': {
      // second "bad guy" will go here
      q: -1,
      r: -1,
      s: 2,
      id: '-1,-1,2',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 5,
      terrain: 'grass',
      startzonePlayerIDs: [''],
    },
    '-1,0,1': {
      q: -1,
      r: 0,
      s: 1,
      id: '-1,0,1',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 5,
      terrain: 'grass',
      startzonePlayerIDs: [''],
    },
    [moveRange2HexWalkTestHexIDs.engagedAdjacentSameLevel_id]: {
      q: 0,
      r: 0,
      s: 0,
      id: moveRange2HexWalkTestHexIDs.engagedAdjacentSameLevel_id,
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 5,
      terrain: 'grass',
      startzonePlayerIDs: [''],
    },
    [moveRange2HexWalkTestHexIDs.safeAdjacentSameLevel_id]: {
      q: 1,
      r: 0,
      s: -1,
      id: moveRange2HexWalkTestHexIDs.safeAdjacentSameLevel_id,
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 5,
      terrain: 'grass',
      startzonePlayerIDs: [''],
    },
    [moveRange2HexWalkTestHexIDs.revealedGlyph_id]: {
      q: 0,
      r: 2,
      s: -2,
      id: moveRange2HexWalkTestHexIDs.revealedGlyph_id,
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 5,
      terrain: 'grass',
      startzonePlayerIDs: [''],
    },
    [moveRange2HexWalkTestHexIDs.beyondRevealedGlyph_id]: {
      q: 0,
      r: 3,
      s: -3,
      id: moveRange2HexWalkTestHexIDs.beyondRevealedGlyph_id,
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 5,
      terrain: 'grass',
      startzonePlayerIDs: [''],
    },
  },
  hexMap: {
    mapId: 'moveRange2HexWalkMap',
    mapShape: 'hexagon',
    mapName: 'Move Range 2Hex Walk Test Map',
    flat: false,
    mapSize: 3,
    hexSize: 10,
    mapWidth: 1,
    mapHeight: 1,
    glyphs: {
      '0,2,-2': {
        hexID: '0,2,-2',
        glyphID: 'move',
        isRevealed: true,
      },
    },
  },
}
